"""Regulatory evidence records — auto-generated by UREA, 22 frameworks, 5 jurisdictions."""
import uuid
from datetime import datetime
from sqlalchemy import String, DateTime, Boolean, JSON, Float, Enum as SAEnum, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.base import Base
import enum


class Framework(str, enum.Enum):
    # India
    CERT_IN  = "CERT-In 2022"
    DPDP     = "DPDP Act 2023"
    RBI      = "RBI Cybersecurity Framework"
    SEBI     = "SEBI CSCRF"
    NCIIPC   = "NCIIPC CII Protection"
    MEITY    = "MeitY/STQC"
    # USA
    FEDRAMP  = "FedRAMP Moderate/High"
    SOC2     = "SOC 2 Type I/II"
    HIPAA    = "HIPAA Breach Notification"
    PCI_DSS  = "PCI-DSS v4.0"
    CMMC     = "CMMC Level 2/3"
    SEC_CYB  = "SEC Cyber Disclosure 8-K"
    CISA_KEV = "CISA KEV Remediation"
    # EU
    GDPR     = "GDPR Art.33/34"
    NIS2     = "NIS2 Directive"
    DORA     = "DORA (Financial)"
    # Canada
    PIPEDA   = "PIPEDA/Bill C-26"
    OSFI_B13 = "OSFI B-13 (Financial)"
    # UAE
    NESA_IAS = "NESA IAS 2023"
    NCA_ECC  = "NCA ECC-1:2018"
    AECERT   = "aeCERT Incident Notification"
    DIFC_DPL = "DIFC DPL 2020"


class RegulatoryEvidence(Base):
    __tablename__ = "regulatory_evidence"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    tenant_id: Mapped[str] = mapped_column(String(36), ForeignKey("tenants.id"), nullable=False, index=True)

    # DFA trace
    incident_ref: Mapped[str] = mapped_column(String(50), nullable=False)
    dfa_state_log: Mapped[list] = mapped_column(JSON, default=list)      # full DFA transition log
    chain_of_custody_hash: Mapped[str] = mapped_column(String(64), nullable=False)  # SHA-256

    # Scores at time of generation
    cdcs_score: Mapped[float] = mapped_column(Float, nullable=False)
    severity: Mapped[str] = mapped_column(String(20), nullable=False)
    event_type: Mapped[str] = mapped_column(String(100), nullable=False)

    # Frameworks triggered
    frameworks_triggered: Mapped[list] = mapped_column(JSON, default=list)
    jurisdictions: Mapped[list] = mapped_column(JSON, default=list)
    reporting_deadlines: Mapped[dict] = mapped_column(JSON, default=dict)  # {framework: iso_deadline}

    # Auto-generated reference numbers
    cert_in_reference: Mapped[str] = mapped_column(String(100), nullable=True)  # CERTIN/2026/05/INC-xxx
    aecert_reference: Mapped[str] = mapped_column(String(100), nullable=True)   # AECERT/2026/05/INC-xxx

    # Auto-generated notification drafts (stored as text)
    cert_in_draft: Mapped[str] = mapped_column(Text, nullable=True)
    dpdp_draft: Mapped[str] = mapped_column(Text, nullable=True)
    rbi_draft: Mapped[str] = mapped_column(Text, nullable=True)
    gdpr_art33_draft: Mapped[str] = mapped_column(Text, nullable=True)
    nis2_draft: Mapped[str] = mapped_column(Text, nullable=True)
    dora_draft: Mapped[str] = mapped_column(Text, nullable=True)
    fedramp_sir_draft: Mapped[str] = mapped_column(Text, nullable=True)
    sec_8k_draft: Mapped[str] = mapped_column(Text, nullable=True)
    hipaa_draft: Mapped[str] = mapped_column(Text, nullable=True)
    pipeda_draft: Mapped[str] = mapped_column(Text, nullable=True)
    nesa_draft: Mapped[str] = mapped_column(Text, nullable=True)

    # Status
    status: Mapped[str] = mapped_column(String(20), default="open")   # open | submitted | closed
    sla_breached: Mapped[bool] = mapped_column(Boolean, default=False)
    submitted_frameworks: Mapped[list] = mapped_column(JSON, default=list)

    # Asset context at time of incident
    asset_attributes: Mapped[dict] = mapped_column(JSON, default=dict)

    # Timestamps
    detected_at: Mapped[datetime] = mapped_column(DateTime, nullable=False)
    evidenced_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    created_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)
    updated_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    incident: Mapped["Incident"] = relationship("Incident", back_populates="regulatory_evidence")
